openapi: 3.0.3

info:
    title: Multi-file API
    version: 1.0.0

paths:
    /users:
        $ref: "./paths/users.yaml"

components:
    schemas:
        User:
            $ref: "./schemas/user.yaml"
        Error:
            $ref: "./schemas/error.yaml"
